- name: Run apt-cacher container
  docker_container:
    name: apt-cacher-ng
    image: apt-cacher-ng
    detach: yes
    state: started
    restart_policy: always
    published_ports: "3142:3142"
    volumes:
      - "apt-cacher-ng-vol:/var/cache/apt-cacher-ng"

# docs.docker.com/storage/volumes/
# docs.ansible.com/ansible/latest/modules/docker_container_module.html
# stackoverflow.com/questions/30449313/how-do-i-make-a-docker-container-start-automatically-on-system-boot
